-- ============================================================
-- ROL COORDINADOR + AGRUPACIÓN POR PROGRAMA
--
-- 1) schools.programa -- nuevo campo para agrupar establecimientos por
--    proyecto/programa (ej. "1bot", "STEAM") en el panel de Docentes.
-- 2) coordinator_assignments -- lista manual de qué docentes puede ver
--    cada coordinador (admin la administra desde el panel de Docentes,
--    botón "Docentes a Cargo").
-- 3) Políticas RLS: un coordinador (teachers.role='coordinador') puede
--    leer SOLO las filas de teachers/teacher_ratings de los docentes que
--    tiene asignados en coordinator_assignments -- nunca todas, nunca
--    escribir. (evaluations y teacher_assignments ya eran de lectura
--    amplia para cualquier autenticado, no hace falta tocarlas.)
--
-- ADITIVO/NO DESTRUCTIVO. Seguro de re-ejecutar. Pegar completo en el
-- SQL Editor de Supabase.
-- ============================================================

-- ------------------------------------------------------------
-- 1. schools.programa
-- ------------------------------------------------------------
alter table public.schools add column if not exists programa text;

-- ------------------------------------------------------------
-- 2. coordinator_assignments
-- ------------------------------------------------------------
create table if not exists public.coordinator_assignments (
  id bigint generated by default as identity primary key,
  coordinator_id uuid not null references public.teachers(id) on delete cascade,
  teacher_id uuid not null references public.teachers(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (coordinator_id, teacher_id)
);

alter table public.coordinator_assignments enable row level security;

drop policy if exists "coordinator_assignments_select_own_or_admin" on public.coordinator_assignments;
create policy "coordinator_assignments_select_own_or_admin"
  on public.coordinator_assignments for select
  using (auth.uid() = coordinator_id or public.is_admin());

drop policy if exists "coordinator_assignments_write_admin_only" on public.coordinator_assignments;
create policy "coordinator_assignments_write_admin_only"
  on public.coordinator_assignments for all
  using (public.is_admin())
  with check (public.is_admin());

-- ------------------------------------------------------------
-- 3. Helper: ¿es este auth.uid() coordinador del docente dado?
-- ------------------------------------------------------------
create or replace function public.is_coordinator_of(p_teacher_id uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.coordinator_assignments ca
    join public.teachers c on c.id = ca.coordinator_id and c.role = 'coordinador'
    where ca.coordinator_id = auth.uid() and ca.teacher_id = p_teacher_id
  );
$$;

-- ------------------------------------------------------------
-- 4. TEACHERS -- amplía la lectura a coordinador para sus docentes
--    asignados (se mantiene: cada uno ve su propia fila, admin ve todas).
-- ------------------------------------------------------------
drop policy if exists "teachers_select_self_or_admin" on public.teachers;
create policy "teachers_select_self_or_admin"
  on public.teachers for select
  using (auth.uid() = id or public.is_admin() or public.is_coordinator_of(id));

-- ------------------------------------------------------------
-- 5. TEACHER_RATINGS -- idem, coordinador puede leer calificaciones de
--    sus docentes asignados (sigue sin poder insertar/editar/borrar).
-- ------------------------------------------------------------
drop policy if exists "teacher_ratings_select_participant_or_admin" on public.teacher_ratings;
create policy "teacher_ratings_select_participant_or_admin"
  on public.teacher_ratings for select
  using (auth.uid() = student_id or auth.uid() = teacher_id or public.is_admin() or public.is_coordinator_of(teacher_id));
