-- ============================================================
-- PROGRAMAS/PROYECTOS COMO CATÁLOGO ADMINISTRADO
--
-- Antes schools.programa era texto libre separado por comas -- cualquiera
-- podía escribir "1bot" en un colegio y "1Bot " (con espacio/mayúscula
-- distinta) en otro, rompiendo la agrupación en el panel de Docentes.
-- Ahora es un catálogo (`programs`) que solo el admin edita, y cada
-- establecimiento se vincula a 1+ programas vía `school_programs`
-- (multi-select real, no texto).
--
-- ADITIVO/NO DESTRUCTIVO -- no borra ni toca schools.programa (queda sin
-- uso, se puede eliminar más adelante si se quiere). Seguro de re-ejecutar.
-- Pegar completo en el SQL Editor de Supabase.
-- ============================================================

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.school_programs (
  school_id bigint not null references public.schools(id) on delete cascade,
  program_id bigint not null references public.programs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (school_id, program_id)
);

alter table public.programs enable row level security;
alter table public.school_programs enable row level security;

drop policy if exists "programs_select_authenticated" on public.programs;
create policy "programs_select_authenticated"
  on public.programs for select
  to authenticated
  using (true);

drop policy if exists "programs_write_admin_only" on public.programs;
create policy "programs_write_admin_only"
  on public.programs for all
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "school_programs_select_authenticated" on public.school_programs;
create policy "school_programs_select_authenticated"
  on public.school_programs for select
  to authenticated
  using (true);

drop policy if exists "school_programs_write_admin_only" on public.school_programs;
create policy "school_programs_write_admin_only"
  on public.school_programs for all
  using (public.is_admin())
  with check (public.is_admin());

-- ------------------------------------------------------------
-- Backfill: migra el texto libre existente en schools.programa (separado
-- por comas) hacia el catálogo nuevo. Seguro de re-ejecutar (on conflict).
-- ------------------------------------------------------------
insert into public.programs (name)
select distinct trim(p)
from public.schools, unnest(string_to_array(programa, ',')) as p
where programa is not null and trim(p) <> ''
on conflict (name) do nothing;

insert into public.school_programs (school_id, program_id)
select s.id, pr.id
from public.schools s
cross join lateral unnest(string_to_array(s.programa, ',')) as p
join public.programs pr on pr.name = trim(p)
where s.programa is not null and trim(p) <> ''
on conflict do nothing;
