-- ============================================================
-- CORREOS DE REENGANCHE (24h / 3 días sin ingresar)
--
-- Tabla de control para no mandar el mismo correo más de una vez por
-- "racha de ausencia" -- se resetea sola porque solo cuenta como
-- "ya enviado" si el registro es MÁS RECIENTE que el último login del
-- usuario (ver notify-inactive-users). Solo la toca la edge function
-- (service role) -- sin políticas de escritura para clientes.
-- ============================================================

create table if not exists public.email_notifications_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  notification_type text not null check (notification_type in ('24h', '3d')),
  sent_at timestamptz not null default now()
);

create index if not exists idx_email_notif_log_user_type on public.email_notifications_log (user_id, notification_type, sent_at desc);

alter table public.email_notifications_log enable row level security;
-- Sin policies de select/insert para clientes -- RLS deniega todo por
-- defecto, solo el service role (edge function) puede leer/escribir.
